### ISSUE TITLE
error while installation via lazy.nvim

### ISSUE THREAD

**Issue by bassamsdata** [cdmill/focus.nvim#1]
Hello! Congrats on the plugin—it's looking really good!

I did run into one issue during installation: a duplicate tag error for "FOCUS" while using lazy.nvim:

```lua
...hare/nvim/lazy/lazy.nvim/lua/lazy/manage/task/plugin.lua:95: Vim:E154: Duplicate tag "FOCUS" in file .../.local/share/nvim/lazy/focus.nvim/doc/focus.txt
```

If possible, would love support for mini.pick as well, as it's a great alternative to telescope. Thanks again!

**Comment by casedami** [comment]
Thanks, I just fixed that. Mini.pick is already supported! But I think it would be good to explicitly mention that in the readme.
